[build]
  command = "pnpm build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NPM_FLAGS = "--no-fund --no-audit"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  NETLIFY_NEXT_PLUGIN_SKIP_INSTALL_CHECK = "true"
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
